### PR TITLE
WIP: Wafl cleanup

### PR DESCRIPTION
**Pull request by olapiv**
Goals for this branch:

- Make multi-processing and re-using data go hand-in-hand (works in Docker now)
- Add CI for Docker implementation (only .yml file missing, see docker_staging_check.sh) @Jacarte do you want to add this to your other workflows?
- Make AFL entrypoint executable by itself (to test against SWAM in debug mode)
- Update README (missing build & run locally and needs general cleanup)
- Add SWAM as a submodule again

### CODE REVIEW

**Comment by olapiv** [comment]
## First draft of CI is done:

* Dockerless:
    * Build with with build.sh
* Docker:
    * Build image
    * Test single image with test_wafl_image.sh
    * Test multiple images with multi-processing.sh
    * Push to Dockerhub

Missing:

* Test build without Docker - @Jacarte, can you do this?

Add-on:

* Wrote script ./wasm-fuzzer/test_socket.sh, to quickly check message-parsing & socket connection - **To be tested**

**Comment by Jacarte** [comment]
ACk @olapiv, sure

**Comment by olapiv** [comment]
@Jacarte, I added wasm-fuzzer/test_wafl_local.sh and it's also in the Github Action that I showed you. Should do it already. Basically just needs testing! Let me know how it goes!

**Comment by monperrus** [comment]
Cool, thanks @olapiv @Jacarte

**Pull request merged**
